### ISSUE TITLE
Setup Server Project

### ISSUE THREAD

**Issue by josemlegal** [josemlegal/sv-landing-page#2]

**Comment by josemlegal** [comment]
### Tasks 

- [ ] Link local repository with this already created remote repository --> https://github.com/josemlegal/sv-landing-page
- [ ] Change head branch name from `master` to `main`.
- [ ] Add dependencies to setup the repo as a restful api.
- [ ] Invite collaborators
